#!/bin/sh
if [ $# -ne 1 ] ; then
	echo "Error:"
	echo "How to Use: start_shadowsocks start/stop/start_on_boot/stop_on_boot"
	exit 1
fi
case "$1" in 
        start)
                echo "start"
		if [ -e "/jffs/config.json" ] ; then
			ss-local -c /jffs/config.json &
		else
			echo "Error:config.json does not exist"
		fi
        ;;
	stop)
		echo "stop"
		killall ss-local
	;;
	start_on_boot)
		echo "start_on_boot"
		nvram set shadowsocks_enable=1
		nvram commit
	;;
	stop_on_boot)
		echo "stop_on_boot"
		nvram set shadowsocks_enable=0
		nvram commit
	;;
        *)
		echo "Error:"
		echo "How to Use: start_shadowsocks start/stop/start_on_boot/stop_on_boot"
        ;;
esac
