include ../common.mak

all:

clean:

install:
	@echo "[settxpower] Installing..."
	@install -d $(INSTALLDIR)/usr/sbin
	@cp settxpower $(INSTALLDIR)/usr/sbin
	@chmod 775 $(INSTALLDIR)/usr/sbin/settxpower

.phony: all clean install
