#!/bin/sh
if [ $# -ne 1 ] ; then
	echo "Error:"
	echo "How to Use: settxpower power"
	echo "power in 1 to 100"
	exit 1
fi
echo Set TxPower $1
nvram set wl_TxPower=$1
nvram set wl0_TxPower=$1
nvram commit

